### ISSUE TITLE
Production back-end 

### ISSUE THREAD

**Issue by amellnik** [JuliaDiffEq/DiffEqOnline#1]
Opening this issue to track progress.  I'm working through [AWSLambda.jl](https://github.com/samoconnor/AWSLambda.jl) to see how much of that code we can reuse if we want to go that route.

**Comment by ChrisRackauckas** [comment]
How would it have to be paid. Do we need to get funding?

**Comment by amellnik** [comment]
Looking at this further I think I'm going to start with Heroku and see if I can get that to work, and I also have a call with JuliaComputing set up for tomorrow morning to hear about their service.   I'll forward it to you in case you're available and interested.   I can support it through low triple-digit $, and if it looks like it's going to scale beyond that we should start looking around.

**Comment by ChrisRackauckas** [comment]
@whilo linked me to this: https://www.chrisstucchio.com/blog/2014/deploying_julia_servers_with_docker.html

**Comment by whilo** [comment]
Oh, you were faster than me :) I like also to commit the docker files in my repo, so it is really easy to deploy some git repo from itself locally.

**Comment by amellnik** [comment]
Nice, it looks like I'm going to be iced-in this weekend so I should have plenty of time to get this set up.

**Comment by amellnik** [comment]
I just got [a base docker image](https://github.com/JuliaDiffEq/DiffEqOnlineServer/commit/0d7e9aaa975cca7be89438043ad7afe58932b0bd) that can use all the needed packages.  The article you and @whilo linked was a big help!

I'm splitting it out into a different repo at the moment since some of the services we might use need it to be a standalone git repo.  (Still trying to decide between Google, Heroku or AWS Lambda if I can get it to work).  If it turns out that it doesn't need to be separate I'll merge it back in.

**Comment by amellnik** [comment]
![image](https://cloud.githubusercontent.com/assets/7132414/21746535/7be704ec-d4fd-11e6-8134-1005f8fe2cb1.png)

I have the server working from within the container!  However, I see a few issues related to this which I will open in the other (possibly temporary) project.

**Comment by ChrisRackauckas** [comment]
Working. Good job!
