### ISSUE TITLE
Optional title/summary?

### ISSUE THREAD

**Issue by amellnik** [JuliaDiffEq/DiffEqOnline#12]
It might be nice to include a user-supplied title or short summary.  Right now we can link to things like [this](http://app.juliadiffeq.org/ode;settings=eyJkaWZmRXFUZXh0IjoiZHggPSBzKih5LXgpXG5keSA9IHgqKHIteikgLSB5XG5keiA9IHgqeSAtIGIqeiIsInBhcmFtZXRlcnMiOiJzPT4xMC4wLCByPT4yOC4wLCBiPT4yLjY2IiwidGltZVNwYW4iOlswLDUwXSwiaW5pdGlhbENvbmRpdGlvbnMiOiIxLCAxLCAxIiwic29sdmVyIjoiVHNpdDUgIiwidmFycyI6Iig6eCwgOnksIDp6KSJ9) but when the user arrives at the page, there's no explanation of what they are looking at.

**Comment by ChrisRackauckas** [comment]
Maybe just allow them to pass a title for the plot? The kwarg is just `title`. It'll make the plots a little nicer for saving too.

**Comment by amellnik** [comment]
Also is there any way to automate the labeling of the axes from `vars`?  [Here](http://www.google.com/url?q=http%3A%2F%2Fapp.juliadiffeq.org%2Fode%3Bsettings%3DeyJkaWZmRXFUZXh0IjoiZHggPSBzKih5LXgpXG5keSA9IHgqKHIteikgLSB5XG5keiA9IHgqeSAtIGIqeiIsInBhcmFtZXRlcnMiOiJzPT4xMC4wLCByPT4yOC4wLCBiPT4yLjY2IiwidGltZVNwYW4iOlswLDUwXSwiaW5pdGlhbENvbmRpdGlvbnMiOiIxLCAxLCAxIiwic29sdmVyIjoiVHNpdDUgIiwidmFycyI6Iig6eCwgOnksIDp6KSJ9&sa=D&sntz=1&usg=AFQjCNGJgetg4hpXgHZm4seW0-fyyahZ3Q) there's no way to tell which axis is which.

**Comment by ChrisRackauckas** [comment]
That's all done in the plot recipe here:

https://github.com/JuliaDiffEq/DiffEqBase.jl/blob/master/src/solutions/solution_interface.jl#L55

There is a way to do it, but exactly how? I'm not sure. I'll take a look at it.

**Comment by ChrisRackauckas** [comment]
Automated labeling is complete.

**Comment by ChrisRackauckas** [comment]
Added titles. Do we still want to do a summary? I think we're good for now.

**Comment by amellnik** [comment]
Looks good now!
