### ISSUE TITLE
Server times out on the first run of the day

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaDiffEq/DiffEqOnline#16]
I noticed that the first compile takes longer than the timeout time, and so the first run of the day will time out. We should find a way to make it run the example problem once every time it restarts so the first run will be snappier.

**Comment by amellnik** [comment]
Closed via https://github.com/JuliaDiffEq/DiffEqOnlineServer/commit/7c18cef33e6ca2242ea8208e4ad873c0bdb16345 (and also deployed).
