### ISSUE TITLE
Increased DiffEq Functionality

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaDiffEq/DiffEqOnline#2]
This issue is to track the progress for adding features to the solver. On the list is:

- [x] Ability to pass the `vars` to the plot recipe (for choosing the values to plot
- [x] An algorithm choice mechanism. Choose from algorithm or default uses alg_hint for stiff vs nonstiff.
- [ ] The ability to choose the number of intermediate points and the plot density
- [x] Other pages (SDEs, DAEs, DDEs) 
  - [x] Split out any common functionality from the ODE component into other components or services.

**Comment by amellnik** [comment]
Let me know if you want any changes on the front to enable these (need a dropdown for the algorithm)?  I'll also start splitting things out into separate page for each of ODEs/SDEs, etc.

**Comment by ChrisRackauckas** [comment]
>(need a dropdown for the algorithm)?

Yes please, if you could show how to make a dropdown and another page I could take it from there.

**Comment by ChrisRackauckas** [comment]
What's the right way to prototype on this now? Same as before? Wondering because with the change to Mux.jl I'm not sure what's the right way to spin this up and try a few things.

**Comment by ChrisRackauckas** [comment]
>I'll also start splitting things out into separate page for each of ODEs/SDEs, etc.

For now we just need a separate page for SDEs. They can be parsed using two boxes instead of one (two functions) using the same macros. Ironically, so call FEM Poisson and FEM Heat equations, but let's not go there yet (unless you want to give it a try: it should just work). DAEs and Delay equations on the other hand would require improving the parser in ParameterizedFunctions.jl, so that may take a bit (I may push for that to be a GSoC project)

**Comment by amellnik** [comment]
Right now I think the best thing is to run `mux_server.jl` from the other repo locally.  Currently it looks for a `PORT` environment variable but we should change it to take a `PORT` command line argument (and the Dockerfile can read the environment variable it gets from Heroku and pass it to the julia script.  Other than that, it should act the same as before although it does now use the solver algorithm selection.  

At some point I'm still planning on moving `mux_server.jl` to the main repo and have the server one just pull it from there when the image is built, but I haven't had a chance yet.

**Comment by ChrisRackauckas** [comment]
Alright. I can wait: I have more than enough DiffEq stuff on my plate already. Just take your time and let me know when it's ready again.

**Comment by ChrisRackauckas** [comment]
One addition to the algs list: if we can, `Rosenbrock23` should be in there so that way there's a method for stiff equations. It would add a dependency on ForwardDiff.jl though.

**Comment by ChrisRackauckas** [comment]
>The ability to choose the number of intermediate points and the plot density

This one is a little bit more difficult if we are sanitizing the inputs since the default is `10*length(sol)`. We could make it a factor of the length that one can choose, but I think it would be common to want to do something like "choose to get the values at 100 points".

**Comment by ChrisRackauckas** [comment]
>Split out any common functionality from the ODE component into other components or services.

Yeah... sorry about the mess...

The reason why those extra parts are inlined is to not have to incur JIT costs. If you ever pass the function `f` to another function, then since every function is its own type, there's a JIT cost. So anything which had a function call is either behind a not-strictly-typed type (i.e. `f::Function`) or is directly inlined into the same place where `f` is created. We could make an

```julia
immutable FunctionWrapper
  f::Function
end
```

which we can use if you want to pull some stuff out, or we can use the `@def` macro to refactor the code a little and have the compiler paste it in the right spots on the first go.

**Comment by ChrisRackauckas** [comment]
If you use the "save to Plotly cloud" option, you can see that it gives the user the data for the plot in a nice spreadsheet and lets them edit the plot. Since that is far more interactivity than we'd ever handle, I think that means we shouldn't think about sending the interpolated data `(newt,newu)` and should instead just try to find a good way to lead users to the Plotly cloud if that's what they want. 

If that's what we do, then all of this:

```julia
    # Build the plot
    sol_handle_time = @elapsed begin
        plotdensity = 10*length(sol)

        vars = DiffEqBase.interpret_vars(vars,sol)
        newt = collect(linspace(sol.t[1],sol.t[end],plotdensity))
        newu = sol(newt)

        dims = length(vars[1])
        for var in vars
          @assert length(var) == dims
        end
        # Should check that all have the same dims!
        plot_vecs,labels = DiffEqBase.solplot_vecs_and_labels(dims,vars,newu,newt,sol,false)

        xflip = (sol.t[end]-sol.t[1]) < 0
    end
    println("Solution handling time: $sol_handle_time")

    plot_time = @elapsed p = plot(plot_vecs...,labels=reshape(labels,1,length(labels)),lw=3,xflip=xflip)
    println("Plot time: $plot_time")    # Build the plot
    sol_handle_time = @elapsed begin
        plotdensity = 10*length(sol)

        vars = DiffEqBase.interpret_vars(vars,sol)
        newt = collect(linspace(sol.t[1],sol.t[end],plotdensity))
        newu = sol(newt)

        dims = length(vars[1])
        for var in vars
          @assert length(var) == dims
        end
        # Should check that all have the same dims!
        plot_vecs,labels = DiffEqBase.solplot_vecs_and_labels(dims,vars,newu,newt,sol,false)

        xflip = (sol.t[end]-sol.t[1]) < 0
    end
    println("Solution handling time: $sol_handle_time")

    plot_time = @elapsed p = plot(plot_vecs...,labels=reshape(labels,1,length(labels)),lw=3,xflip=xflip)
    println("Plot time: $plot_time")
```

can just go back to the plot recipe:

```julia
plot_time = @elapsed p = plot(sol)
```

The timings from last night show that, if we aren't trying to use the interpolated data elsewhere, there is no performance difference for doing this. And this will work for all ODEs/SDEs/DAEs/etc. with no special-casings necessary (whereas the other way we would need to special case for the fast that SDEs shouldn't interpolate). 

Let me know if you think this is the right direction.

**Comment by ChrisRackauckas** [comment]
If we go back to the plot recipe, then the only difference between the ODEs and SDEs is:

- SDEs need a second function
- SDEs will need to define a different problem (but the solution will act the same)
- It will need to do the init dt choice a little differently.

For SDEs, this code:

https://github.com/JuliaDiffEq/DiffEqOnlineServer/blob/master/api/mux_server.jl#L114

needs to swap to this variant:

https://github.com/JuliaDiffEq/StochasticDiffEq.jl/blob/master/src/initdt.jl#L1

If you want an easy way to refactor that a little bit, we can use the [`@def` macro](https://github.com/JuliaDiffEq/DiffEqBase.jl/blob/master/src/utils.jl#L19) to define two macros which inline the calculation, and do:

```julia
if typeof(prob) <: AbstractODESolution
  @ode_calculate_init_dt
elseif typeof(prob) <: AbstractSDESolution
  @sde_calculate_init_dt
end
```

with

```julia
@def ode_calculate_init_dt
      dtmax = tspan[end]-tspan[1]
      tdir = sign(dtmax)
      abstol = 1e-6; reltol = 1e-3
      ## Compute initdt without JIT lag
      t = tspan[1]
      f₀ = similar(u0./t); f₁ = similar(u0./t); u₁ = similar(u0)
      sk = abstol+abs.(u0)*reltol
      d₀ = OrdinaryDiffEq.ODE_DEFAULT_NORM(u0./sk)
      f(t,u0,f₀)
      d₁ = OrdinaryDiffEq.ODE_DEFAULT_NORM(f₀./sk)
      if d₀ < 1/10^(5) || d₁ < 1/10^(5)
        dt₀ = 1/10^(6)
      else
        dt₀ = (d₀/d₁)/100
      end
      dt₀ = min(dt₀,tdir*dtmax)
      @inbounds for i in eachindex(u0)
         u₁[i] = u0[i] + tdir*dt₀*f₀[i]
      end
      f(t+tdir*dt₀,u₁,f₁)
      tmp = (f₁.-f₀)./(abstol+abs.(u0)*reltol)
      d₂ = OrdinaryDiffEq.ODE_DEFAULT_NORM(tmp)/dt₀
      if max(d₁,d₂)<=1/10^(15)
        dt₁ = max(1/10^(6),dt₀*1/10^(3))
      else
        dt₁ = 10.0^(-(2+log10(max(d₁,d₂)))/OrdinaryDiffEq.alg_order(alg))
      end
      dt = tdir*min(100dt₀,dt₁)
end
```

and

```julia
@def sde_calculate_init_dt
  d₀ = norm(u0./(abstol+abs.(u0)*reltol),2)
  if typeof(u0) <: Number
    f₀ = f(t,u0)
    g₀ = 3g(t,u0)
  else
    f₀ = similar(u0)
    g₀ = similar(u0)
    f(t,u0,f₀)
    g(t,u0,g₀); g₀.*=3
  end

  d₁ = norm(max(abs.(f₀.+g₀),abs.(f₀-g₀))./(abstol+abs.(u0)*reltol),2)
  if d₀ < 1e-5 || d₁ < 1e-5
    dt₀ = 1e-6
  else
    dt₀ = 0.01*(d₀/d₁)
  end
  dt₀ = min(dt₀,tdir*dtmax)
  u₁ = u0 + tdir*dt₀*f₀
  if typeof(u0) <: Number
    f₁ = f(t+tdir*dt₀,u₁)
    g₁ = 3g(t+tdir*dt₀,u₁)
  else
    f₁ = similar(u0)
    g₁ = similar(u0)
    f(t,u0,f₁)
    g(t,u0,g₁); g₁.*=3
  end
  ΔgMax = max(abs.(g₀-g₁),abs.(g₀+g₁))
  d₂ = norm(max(abs.(f₁.-f₀.+ΔgMax),abs.(f₁.-f₀.-ΔgMax))./(abstol+abs.(u0)*reltol),2)/dt₀
  if max(d₁,d₂)<=1e-15
    dt₁ = max(1e-6,dt₀*1e-3)
  else
    dt₁ = 10.0^(-(2+log10(max(d₁,d₂)))/(order+.5))
  end
  dt = tdir*min(100dt₀,dt₁)
end
```

to inline it all. I know some people aren't a fan of this type of macro-abuse though! But with that everything in the main function should be setup for SDEs.

**Comment by ChrisRackauckas** [comment]
A commited a version where SDEs is working. Since DAEs and DDEs would require a big improvement to the parser of ParameterizedFunctions.jl, this is a good place to stop the expansion for now. However, once it can parse DAEs and DDEs, essentially the exact same pipeline will work for them, so there's no change needed there.

The remaining question is then:

>The ability to choose the number of intermediate points and the plot density

Do we want to offer this? Or do you think it would be abused? Right now the plots automatically choose the density to be `10*length(sol)`, so most plots should look good. If we allow users to choose the number of points or an integer factor (times length) of numbers of points, this may improve the plot in some cases, but could greatly increase the amount of work on the server and the amount of data that needs to be transferred back and forth. I am inclined to say that if a user really wants that, we introduce them to Julia 👍 .

So at least for now I'll close this and further improvements can be addressed individually.
