### ISSUE TITLE
Store full details of input in URL matrix parameter

### ISSUE THREAD

**Issue by amellnik** [JuliaDiffEq/DiffEqOnline#3]
TODO: Wrap all input parameters under a single object and store in the url.  This will allow users to link to a page with all the details of a specific differential equation filled in.  Loading the root url should fill in default values.

**Comment by ChrisRackauckas** [comment]
I wasn't sure how to handle this so I'll leave this to you.

**Comment by amellnik** [comment]
Closed with https://github.com/JuliaDiffEq/DiffEqOnline/commit/0c7c08a0b53678c482cc1b16481b21aa75efac7e!
