### ISSUE TITLE
Error handling on server?

### ISSUE THREAD

**Issue by amellnik** [JuliaDiffEq/DiffEqOnline#4]
Right now it looks like all errors are generically captured by `JuliaWebAPI` [here](https://github.com/JuliaWeb/JuliaWebAPI.jl/blob/f9d31c313bb399ae422fcf2727f42d4a15f9956f/src/APIResponder.jl#L83).  This means that any error that occurs on the server always returns a 500 server error.  We may need more detail than this -- it would be nice to return different errors for solutions that don't converge, overflow errors, problems with parsing the equation inputs, etc.  

TODO: Figure out if we can do this on our own or if it will require a change in `JuliaWebAPI`.

**Comment by ChrisRackauckas** [comment]
Is there a good way to pass error data back? I tried

```
dx = σ*(y-x)
dy = x*(ρ-z) - y
dz = x*y - β*z
```

with 

```
σ=>10.0 ρ=>28.0, β=2.66
```

and 

```
1.0, 0.0, 0.0
```

which should solve the Lorenz equations, but I get no response back.

**Comment by amellnik** [comment]
This error is actually in the client -- the data is being passed as part of a url to the back-end and the base64 string encoding thing I'm using can't deal with fancy characters.  You can see it if you open the console on the browsers.

 However, even replacing the greek characters with ascii letters I was getting an error.  The logs showed

```
2017-01-12T02:10:40.948459+00:00 app[web.1]: Diff equ: begin  # none, line 2:
2017-01-12T02:10:40.948932+00:00 app[web.1]:     dx = s * (y - x) # none, line 3:
2017-01-12T02:10:40.949460+00:00 app[web.1]:     dy = x * (r - z) - y # none, line 4:
2017-01-12T02:10:40.949818+00:00 app[web.1]:     dz = x * y - b * z
2017-01-12T02:10:40.949879+00:00 app[web.1]: end
2017-01-12T02:10:40.955776+00:00 app[web.1]: Params: Expr[:(s => (10.0r => 28.0)),:(b = 2.66)]
2017-01-12T02:10:40.956047+00:00 app[web.1]: tspan: (0.0,10.0)
2017-01-12T02:10:40.956477+00:00 app[web.1]: u0: [1.0,0.0,0.0]
2017-01-12T02:10:40.973357+00:00 app[web.1]: WARNING: Symbolic calculations could not initiate. Likely there's a functio
n which is not differentiable by SymEngine.
2017-01-12T02:10:40.998518+00:00 app[web.1]: WARNING: Method definition (::Type{ParameterizedFunctions.{"diffEqText":"dx
 = s*(y-x)\ndy = x*(r-z) - y\ndz = x*y - b*z","timeSpan":[0,10],"parameters":["s=>10.0r=>28.0","b=2.66"],"initialConditi
ons":["1.0","0.0","0.0"],"solver":"Tsit5 "}})(Expr, Array{Expr, 1}, Array{SymEngine.Basic, 1}, Array{Expr, 1}, Array{Exp
r, 1}, Array{Symbol, 1}, Array{SymEngine.Basic, 1}, Array{SymEngine.Basic, 2}, Array{SymEngine.Basic, 2}, Array{SymEngin
e.Basic, 2}, Array{SymEngine.Basic, 2}, Array{SymEngine.Basic, 2}, Array{SymEngine.Basic, 2}, Array{SymEngine.Basic, 2},
 Array{SymEngine.Basic, 2}, Expr, Expr, Expr, Expr, Expr, Expr, Expr, Expr, Expr, Expr, Expr, Array{Symbol, 1}, Expr) in
 module ParameterizedFunctions at /opt/julia/v0.5/ParameterizedFunctions/src/maketype.jl:25 overwritten at /opt/julia/v0
.5/ParameterizedFunctions/src/maketype.jl:25.
2017-01-12T02:10:41.001688+00:00 app[web.1]: WARNING: Method definition (::Type{ParameterizedFunctions.{"diffEqText":"dx
 = s*(y-x)\ndy = x*(r-z) - y\ndz = x*y - b*z","timeSpan":[0,10],"parameters":["s=>10.0r=>28.0","b=2.66"],"initialConditi
ons":["1.0","0.0","0.0"],"solver":"Tsit5 "}})(Any, Any, Any, Any, Any, Any, Any, Any, Any, Any, Any, Any, Any, Any, Any,
 Any, Any, Any, Any, Any, Any, Any, Any, Any, Any, Any, Any, Any) in module ParameterizedFunctions at /opt/julia/v0.5/Pa
rameterizedFunctions/src/maketype.jl:25 overwritten at /opt/julia/v0.5/ParameterizedFunctions/src/maketype.jl:25.
2017-01-12T02:10:41.033584+00:00 app[web.1]: WARNING: Method definition (::Type{ParameterizedFunctions.{"diffEqText":"dx
 = s*(y-x)\ndy = x*(r-z) - y\ndz = x*y - b*z","timeSpan":[0,10],"parameters":["s=>10.0r=>28.0","b=2.66"],"initialConditi
ons":["1.0","0.0","0.0"],"solver":"Tsit5 "}})() in module ParameterizedFunctions at /opt/julia/v0.5/ParameterizedFunctio
ns/src/maketype.jl:72 overwritten at /opt/julia/v0.5/ParameterizedFunctions/src/maketype.jl:72.
2017-01-12T02:10:41.034455+00:00 app[web.1]: WARNING: Method definition Type(Array{Any, 1}, Type{ParameterizedFunctions.
{"diffEqText":"dx = s*(y-x)\ndy = x*(r-z) - y\ndz = x*y - b*z","timeSpan":[0,10],"parameters":["s=>10.0r=>28.0","b=2.66"
],"initialConditions":["1.0","0.0","0.0"],"solver":"Tsit5 "}}) in module ParameterizedFunctions overwritten.
2017-01-12T02:10:41.234368+00:00 heroku[router]: at=info method=GET path="/solveit/eyJkaWZmRXFUZXh0IjoiZHggPSBzKih5LXgpX
G5keSA9IHgqKHIteikgLSB5XG5keiA9IHgqeSAtIGIqeiIsInRpbWVTcGFuIjpbMCwxMF0sInBhcmFtZXRlcnMiOlsicz0+MTAuMHI9PjI4LjAiLCJiPTIuN
jYiXSwiaW5pdGlhbENvbmRpdGlvbnMiOlsiMS4wIiwiMC4wIiwiMC4wIl0sInNvbHZlciI6IlRzaXQ1ICJ9" host=diffeqonline.herokuapp.com req
uest_id=8d9b3d8a-6ebf-4e11-a2e4-6ee3a0f515a0 fwd="173.87.34.11" dyno=web.1 connect=1ms service=275ms status=500 bytes=55
20
```
Which was not very helpful since the real error was not captured.  However, I could find the actual error by going to the [api call directly](http://diffeqonline.herokuapp.com/solveit/eyJkaWZmRXFUZXh0IjoiZHggPSBzKih5LXgpXG5keSA9IHgqKHIteikgLSB5XG5keiA9IHgqeSAtIGIqeiIsInRpbWVTcGFuIjpbMCwxMF0sInBhcmFtZXRlcnMiOlsicz0+MTAuMHI9PjI4LjAiLCJiPTIuNjYiXSwiaW5pdGlhbENvbmRpdGlvbnMiOlsiMS4wIiwiMC4wIiwiMC4wIl0sInNvbHZlciI6IlRzaXQ1ICJ9).  It turns out there was a missing comma, and correcting for it, it works.

![image](https://cloud.githubusercontent.com/assets/7132414/21874498/1306b6f4-d82a-11e6-80da-0783d0690fc6.png)

The big problem is that Mux eats all the errors and returns jokey response pages like the one above.  I need a way (may require a patch to Mux) to instead return a json response like

```json
{
  "error": true,
  "error_msg": "UndefVarError: r not defined ..."
}
```

when there's an error.  

Also we totally need an option to either plot each variable as a fn of t or on an x-y or x-y-z plot to best show off things like the Lorenz.

**Comment by ChrisRackauckas** [comment]
>Also we totally need an option to either plot each variable as a fn of t or on an x-y or x-y-z plot to best show off things like the Lorenz.

Yes, it's already available in the plot recipes via the `vars` keyword argument, but it just hasn't been exposed to the web yet.

**Comment by ChrisRackauckas** [comment]
Where could I find those logs?

**Comment by amellnik** [comment]
If you install the Heroku cli you can `heroku logs` from inside the repo folder.

**Comment by amellnik** [comment]
What should the input for vars look like?

**Comment by ChrisRackauckas** [comment]
http://docs.juliadiffeq.org/latest/basics/plot.html#Choosing-Variables-1

It's documented here, with an example below. Either integers for the components, or the symbols for the variables work. I don't think I implemented a symbol to work for the independent variable though, but I think I should just hardcode it in as `:t` for time. A special-case for that would need to be added here:

https://github.com/JuliaDiffEq/DiffEqBase.jl/blob/master/src/solutions/solution_interface.jl#L124

**Comment by amellnik** [comment]
Closed via https://github.com/JuliaDiffEq/DiffEqOnline/commit/3f1e00afb2bc65cf4e5a8d57e04020cdb5831205 and https://github.com/JuliaDiffEq/DiffEqOnlineServer/commit/3e424cf3a5ed70b20a7e4f1cb1acc5d1ff5d6a19.
