### ISSUE TITLE
Rename and Migrate

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaDiffEq/DiffEqOnline#5]
This project is growing far beyond "demo" and into a really cool app. I think we should rename the repo and migrate it over to JuliaDiffEq. What's a good name?

**Comment by amellnik** [comment]
Agreed -- maybe DiffEqWebTool, DiffEqOnline or similar.  I noticed that the JuliaDiffEq organization web site is hosted through github at the moment, but maybe it would be a good time to snag a domain that we could use for this tool, if nothing else.

**Comment by ChrisRackauckas** [comment]
I set things up with juliadiffeq.org (well, the main site might take a little bit longer to fix itself, but the docs are already up). Can I get admin privileges to move the repo to JuliaDiffEq and setup the CNAME? I am thinking of pointing it to app.juliadiffeq.org , and then we just need a name. DiffEqOnline sounds good.

**Comment by ChrisRackauckas** [comment]
Completed. Though the gh-pages no longer loads: http vs https related?

**Comment by amellnik** [comment]
The link format is different for projects owned by an organization I think
- I'll look into it, but we should probably just start using the non-GitHub
domain.

(Please excuse brevity and errors, sent from a mobile device.)

**Comment by ChrisRackauckas** [comment]
The server has more than enough power to host this (it's what I am using for my blog which gets quite a bit of traffic). If it needs to move off of Github that's fine: we would just need some way of "linking the code". I've never done a website whose code comes from a Github repo before (and had it be a non gh-pages site) so I am not sure how to set that up.

**Comment by amellnik** [comment]
Angular-cli has a built-in command which builds the site in production mode in the `/dist` folder.  [This line](https://github.com/JuliaDiffEq/DiffEqOnline/blob/master/package.json#L12) lets you run `npm run prodbuild` to do that while also rewriting the links.  The version that's there now might work but just needs a different base href, so you might just be able to modify that one line..  Depending on how your hosting is setup, you can then ftp that folder over by hand (or we can write this into a gulp task or similar to make it easier to deploy).  

Who is the hosting through and what's it running on?  We might need to use a custom `.htaccess` or modify a setting or two to get the routing to work.  (On github pages the workaround was to make a copy of `index.html` and name it `404.html`)

**Comment by ChrisRackauckas** [comment]
It's running on a Bluehost cloud plan:

http://cloud.bluehost.com/products/cloud-sites

The performance plan. I can upgrade the plan to have a dedicated IP if needed.

**Comment by amellnik** [comment]
Looks good, their site says you can use `.htaccess` overwrites so we probably just need to add one to the project in the same folder as `index.html`.  I think the first solution [here](http://stackoverflow.com/questions/34816025/angular2-routing-deep-linking-not-working-with-apache-404) is probably correct but haven't tested it yet.

**Comment by ChrisRackauckas** [comment]
I can get you FTP access to that domain if needed. There's nothing there though since everything is gh-pages, so I am not sure what you're supposed to due (since there is no index.html for that folder, and it would be in the `apps` subdomain).

**Comment by amellnik** [comment]
If you send me the FTP information I can set up a deploy script for the front end.
