### ISSUE TITLE
Front end down

### ISSUE THREAD

**Issue by amellnik** [JuliaDiffEq/DiffEqOnline#9]
It looks like the domain is serving up an older version of `index.html` than the one that is on the ftp site at the moment -- any idea what might be causing this?  Is there some sort of caching set up?

**Comment by amellnik** [comment]
When I go to the domain I get a file which contains `<script type="text/javascript" src="scripts.4e65d38e37a65b9112ef.bundle.js"></script><script type="text/javascript" src="main.84db472f89bc93390874.bundle.js"></script></body>` but the one on the ftp contains `<script type="text/javascript" src="inline.js"></script><script type="text/javascript" src="styles.1471973153702e9bc97b.bundle.js"></script><script type="text/javascript" src="scripts.eabf308e166c5f92ec8d.bundle.js"></script><script type="text/javascript" src="main.5f8b436ca3baa7f42a6f.bundle.js"></script></body>` which references the correct files.

**Comment by amellnik** [comment]
The error we see right now `Uncaught SyntaxError: Unexpected token <` is because it tries to load `main.84db472f89bc93390874.bundle.js` which doesn't exist, and our .htaccess rule does it's thing and returns `index.html`, which gives this error since it's not js.  ([Details here](http://stackoverflow.com/questions/31529446/unexpected-token-in-first-line-of-html)).

**Comment by ChrisRackauckas** [comment]
Yeah, this is this comment:

https://github.com/JuliaDiffEq/DiffEqOnline/issues/8#issuecomment-272714351

It seems to go down for a bit and then fix itself over time. No idea why the delay is so long though.

**Comment by amellnik** [comment]
Hmm yeah maybe look into the documentation or help section for your host -- I wonder if there's a way to reset the cache.

**Comment by ChrisRackauckas** [comment]
Yeah, it's back up now. From the chat logs it looks like it puts it down for about 30 minutes.

**Comment by ChrisRackauckas** [comment]
Found out how to reset the cache to make this faster.
